---
apiVersion: v1
kind: Namespace
metadata:
  name: vidya
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vidya
  name: deployment1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app1
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app1
    spec:
      containers:
      - image: 497961877860.dkr.ecr.ap-southeast-1.amazonaws.com/yellow:latest
        imagePullPolicy: Always
        name: app1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: vidya
  name: service1
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: vidya
  name: ingress1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service1
              port:
                number: 80
