name: Terraform Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./eks

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Run command
      run: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp

    - name: Run command
      run: sudo mv /tmp/eksctl /usr/local/bin

    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Plan
      run: terraform plan -input=false -out=plan.tfplan

    - name: Terraform Apply
      run: terraform apply -input=false plan.tfplan
